### ISSUE TITLE
No need to save order

### ISSUE THREAD

**Issue by jamiepittock** [bossanova808/CommerceFriendlyOrderNumbers#2]
Hey - 

In your `onBeforeOrderCompleteHandler()` you call the `saveOrder()` at the end but I don't think that's needed. 

You're using the `onBeforeOrderComplete` event so the order will be saved directly after this anyway. 

At the moment the order will get saved twice.

**Comment by bossanova808** [comment]
Hmm, not sure that's _necessarily_ true, although it certianly sounds right - but I have a nagging memory the setContentFromPost required the save to be there (rather than relying on the coming save) - for it to work...but that may not be right?

Have you actually tested it without the saveOrder there?

**Comment by jamiepittock** [comment]
I've been using it for a few months without the `saveOrder` and I haven't noticed any issues.

You're making me doubt myself now though!

**Comment by bossanova808** [comment]
Hah - it's most likely fine. I have a lot of things hooking in so it might well have been just an extra precaution on my part.

It's kinda minor though - a saveOrder will add at most a few ms.  I might just leave it just in case of unexpected consequence with my own scenario - I wasn't even using this plugin version till recently, I just spun it out for others...I have it in my general business logic.  But I have moved to using it now...
